### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sgrif** [sgrif/yaqb#13]
This is my biggest call to action for anybody interested. While I will absolutely write all the docs if needed, I do strongly believe that the best flow for this is to have people who didn't implement something ask questions, and find usage that way, as it forces an explanation targeted at people not familiar with the framework.

This is by far the biggest blocker for 0.1, and probably the easiest way to get started. If you're interested in helping, comment here, or shoot me an email (it's on my profile). I will take as much time as is needed to explain usage.

**Comment by mikeastock** [comment]
I am interested in helping write documentation as I try to use the library! I believe @mcasper is willing to help as well. We are building a simple API backend using Iron and would love to try to use yaqb.

**Comment by sgrif** [comment]
@mikeastock Excellent! I'm happy to help however I can. Feel free to ping with any specifics. I'm trying to get the bare minimum getting started stuff out the door tonight.

**Comment by sgrif** [comment]
Documentation can always be improved, but I believe we have the minimum acceptable level of documentation for all modules. I think we're good to go for 0.1.

PRs to improve documentation, no matter how minor, are always welcome.
