### ISSUE TITLE
Status of DbResult

### ISSUE THREAD

**Issue by mikeastock** [sgrif/yaqb#21]
The README shows it as the return type for insert but the [source](https://github.com/sgrif/yaqb/blob/3b962733396430e25f72f32dcee03051db177de1/yaqb/src/connection/mod.rs#L167-L168) shows `Result` as the return type. Is the end goal to use `DbResult` over `Result`?

**Comment by sgrif** [comment]
The goal is not not overload prelude, but I've been referencing `yaqb::result::Result` when I use that name.
