### ISSUE TITLE
Unable to build using modules

### ISSUE THREAD

**Issue by mfpiccolo** [sgrif/yaqb#28]
I am trying to build using the latest master but a bunch of unimplemented errors now. It was working on master and when I pointed to the newest master on yaqb there was a serde compatibility issue because of quasi.  I removed serde and now I am trying to get the same functionality but I am unable to compile.

I can post the code in the issue but it may just be easier to link.

Here are the two files from my try-compile branch: 
https://github.com/mfpiccolo/yaqb_test/blob/try-compile/src/models/post.rs
https://github.com/mfpiccolo/yaqb_test/blob/try-compile/src/models/user.rs

Any idea why I would be getting the errors like: 

```
error: the trait `yaqb::query_source::Queriable<(yaqb::types::Integer, yaqb::types::VarChar, yaqb::types::Nullable<yaqb::types::VarChar>)>` is not implemented for the type `models::user::User
```

**Comment by sgrif** [comment]
It looks like you're using nightly, not syntex. You need to specify a few things in `Cargo.toml`. https://github.com/sgrif/yaqb/tree/master/yaqb_codegen#using-on-nightly

**Comment by sgrif** [comment]
(Sorry, the instability should settle a bit on Monday when I release 0.1)

**Comment by mfpiccolo** [comment]
No worries.  I had not seen the codegen docs yet.  Thanks!
