### ISSUE TITLE
#insert error: unable to infer enough type information about `_`

### ISSUE THREAD

**Issue by mfpiccolo** [sgrif/yaqb#8]
@sgrif I am setting up a simple server with yaqb and I am running into a problem with insert that I cannot get past.  I ultimately keep running into this error when trying to use insert with a NewUser struct.

```
src/models/user.rs:41:10: 41:49 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
src/models/user.rs:41     conn.insert(&self::users::table, &new_users);
```

If I switch to insert_returning_count it works fine.  

Here is the line causing the error:

https://github.com/mfpiccolo/yaqb_test/blob/master/src/models/user.rs#L40

**Comment by mfpiccolo** [comment]
It also compiles if I set a return value for the function:

```  
pub fn insert(new_users: Vec<NewUser>) -> Vec<User> {
  User::conn().insert(&self::users::table, &new_users).unwrap().collect()
}
```

**Comment by sgrif** [comment]
This is a hole in the docs. If you're not going to use the return value, you should use `insert_returning_count` (which I'm open to other names for as well). `insert` is only intended to be used when you need the created record (either for ids, timestamps, or the result of some default value)

**Comment by sgrif** [comment]
Leaving this open since there's an actionable problem

**Comment by sgrif** [comment]
Fixed by https://github.com/sgrif/yaqb/commit/58b73cbd7903de44d63a7ce45cb53ed2e5750885
